export const DefaultData = [
  {
    usuario: "arroz con leche",
    correo: "nicoll123@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "aguacate",
    correo: "aguacate@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "arroz con leche",
    correo: "nicoll123@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "arroz con leche",
    correo: "nicoll123@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "arroz con leche",
    correo: "nicoll123@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Patacón",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Quesito",
    correo: "quesito@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
  {
    usuario: "Carlita",
    correo: "Patacon@gmail.com",
    estado: "activo",
    cambioestado: "Sancionar",
  },
];
